[package]
name = "timefusion"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
datafusion = "44.0.0"  
arrow = "54.1.0"
uuid = { version = "1.13", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.138"
async-trait = "0.1.86"
env_logger = "0.11.6"
log = "0.4.25"
color-eyre = "0.6.3"
arrow-schema = "54.1.0"
regex = "1.11.1"
deltalake = { version = "0.24.0",  features=["datafusion","s3"]}
chrono = "0.4.39"
pgwire = "0.28.0"
futures = "0.3.31"
bytes = "1.4"
tokio-rustls = "0.26.1"
sled = "0.34.7"
actix-web = "4.9.0"
datafusion-postgres = "0.3.0"
datafusion-functions-json = "0.45.0"
anyhow = "1.0.95"
tokio-util = "0.7.13"
tracing-subscriber ={ version = "0.3.19", features = ["env-filter"]}
tracing = "0.1.41"
prometheus = "0.13.4"
dotenv = "0.15.0"
task = "0.0.1"
sqlparser = "0.54.0"
rustls-pemfile = "2.2.0"
rustls = "0.23.23"
actix-service = "2.0.2"
lazy_static = "1.5.0"
bcrypt = "0.17.0"
opentelemetry = "0.28.0"
opentelemetry-otlp = "0.28.0"
tracing-opentelemetry = "0.29.0"
bincode = "1.3.3"
opentelemetry_sdk = { version = "0.28.0", features = ["experimental_async_runtime"] }
