name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Preset Image Name
        id: preset_image_name
        run: |
          echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.preset_image_name.outputs.IMAGE_URL }}

      - id: deploy
        name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPTAINROVER_SERVER }}
          app: ${{ secrets.CAPTAINROVER_APP_NAME }}
          token: ${{ secrets.CAPTAINROVER_APP_TOKEN }}
          image: ${{ steps.preset_image_name.outputs.IMAGE_URL }}

      - name: Show Deployment Output
        run: |
          echo "Deployment URL: ${{ steps.deploy.outputs.url }}"
